# build environment
FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /app

COPY *.sln ./
COPY CapWatchBackend.Application/*.csproj ./CapWatchBackend.Application/
COPY CapWatchBackend.DataAccess.MongoDB/*.csproj ./CapWatchBackend.DataAccess.MongoDB/
COPY CapWatchBackend.Domain/*.csproj ./CapWatchBackend.Domain/
COPY CapWatchBackend.WebApi/*.csproj ./CapWatchBackend.WebApi/
COPY CapWatchBackend.WebApi.Tests/*.csproj ./CapWatchBackend.WebApi.Tests/
COPY CapWatchBackend.DataAccess.MongoDB.Tests/*.csproj ./CapWatchBackend.DataAccess.MongoDB.Tests/
COPY CapWatchBackend.Application.Tests/*.csproj ./CapWatchBackend.Application.Tests/

RUN dotnet restore

COPY . ./

RUN dotnet publish -c Release -o out
RUN echo "https://ftp.halifax.rwth-aachen.de/alpine/edge/community/" >> /etc/apk/repositories && \
    apk update && \
    apk add openjdk11 \

EXPOSE 80

ENTRYPOINT ["dotnet", ""]
